import type { Metadata } from "next";
import "./globals.css";
import { onAuthStateChanged } from "firebase/auth";
import auth from "@/lib/firebase";
import ToastContextProvider from "@/providers/ToastContextProvider";
import NavBar from "@/components/NavBar";

export const metadata: Metadata = {
  title: "Amplify Dentistry",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <ToastContextProvider>
          <div className="z-0 sticky top-2 right-0">
            <NavBar />
          </div>
          {children}
        </ToastContextProvider>
      </body>
    </html>
  );
}
