import type { Metadata } from "next";
import "./globals.css";
import { onAuthStateChanged } from "firebase/auth";
import auth from "@/lib/firebase";

export const metadata: Metadata = {
  title: "Amplify Dentistry",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
