"use client"
import type { Metadata } from "next";
import "./globals.css";
import AuthContextProvider from "@/lib/AuthContextProvider";
import { createContext, useEffect, useState } from "react";
import { onAuthStateChanged } from "firebase/auth";
import { auth } from "@/lib/firebase";

// export const metadata: Metadata = {
//   title: "Amplify Dentistry",
//   description: "Generated by create next app",
// };
export const UserContext = createContext({})
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  
  const [user, setUser] = useState<any | null>(null)
  useEffect(() => {
    onAuthStateChanged(auth, user => {
      if(user){
        setUser(user)
      } else {
        setUser(null)
      }
    })
  },[])

  return (
    <html lang="en">
      <body>
        {children}
      </body>
    </html>
  );
}
